### PR TITLE
Automated windows build

### PR DESCRIPTION
**Pull request by stefanfoulis**
- [x] basic build for windows
- [x] actually test the resulting binary on a windows machine ( @vxsx )
- [ ] ~~auto create github release with binary for releases~~ later
  - https://www.appveyor.com/docs/deployment/github/

For the other platforms:
- https://docs.travis-ci.com/user/multi-os/
- https://docs.travis-ci.com/user/deployment/releases/
- https://docs.travis-ci.com/user/osx-ci-environment/

### CODE REVIEW

**Comment by Chive** [comment]
can we do automated mac build as well? :D

**Comment by stefanfoulis** [comment]
@Chive yes we can do an automated osx build on travis.

**Comment by Chive** [comment]
@stefanfoulis are you gonna do that as well? :)

**Comment by stefanfoulis** [comment]
@Chive not right now. But yeah.

**Pull request merged**
