### PR TITLE
Mention Desktop App in workspace setup message

### PR DESCRIPTION
**Pull request by stefanfoulis**
```
$ divio project setup myproject
Creating workspace

[...]

Your workspace is setup and ready to start.

For Desktop Application:
 - click on the 'Start' button

For Terminal:
 - change directory to 'myproject'
 - run 'divio project up'
```

### CODE REVIEW

**Comment by Chive** [comment]
@stefanfoulis how about a command flag instead?

**Comment by stefanfoulis** [comment]
@Chive good idea. How should I call  the option?

* ``--desktop-app``
* ``--for-gui``
* ...

**Comment by stefanfoulis** [comment]
@Chive and pass along the attribute to all the various functions? Or do you already have some other way to keep that state somewhere?

**Comment by stefanfoulis** [comment]
Baby steps. I'm going to merge this PR as-is. Then we can add the flag (which is much more involved and also needs changes in the Desktop App) later.

**Comment by Chive** [comment]
@stefanfoulis no network :( there should be a context variable passed first thing to the cli command which (iirc) is passed down to the setup itself.

**Pull request merged**
