### PR TITLE
black formatting, python3, make lint

### LINKED ISSUE #215: remove usage of unicode()
found here 
https://github.com/divio/divio-cli/blob/675b07cda584f1ddb87b320da96b0ba79c2a3437/divio_cli/api_requests.py#L92

### PR DESCRIPTION
**Pull request by kinkerl**
reformatting everything with black

fixes #215

### CODE REVIEW

**Comment by vxsx** [comment]
not much of a review from me, but it should be ok.
does this drop py2 support?

**Comment by kinkerl** [comment]
no. the only code change is a "unicode" to "str". the rest is formatting. will merge once the travis issues are sorted out

**Comment by kinkerl** [comment]
added new error messages as well:

RESOURCE_NOT_FOUND_ANONYMOUS = "Resource not found"
RESOURCE_NOT_FOUND = "Resource not found. You are logged in as '{login}', please check if you have permissions to access the ressource"

**Comment by glasnt** [comment]
@kinkerl let me know if you want the test suite to test any Python versions other than 3.6.3

**Pull request merged**
