### PR TITLE
Fix yaml package name and optional cryptography package

### PR DESCRIPTION
**Pull request by stefanfoulis**

### CODE REVIEW

**Comment by Chive** [comment]
How is this gonna be handled in binary packages? Always included by default?

**Comment by stefanfoulis** [comment]
I've not looked into including it with the binary yet. But yes: the binaries should contain it eventually

**Comment by Chive** [comment]
@stefanfoulis I mean because of the `pip install` hint that you've put in - that doesn't really help a user if he's installed the binary does it?

**Comment by stefanfoulis** [comment]
@Chive I agree. But the command in question is also not official and you can't even use it unless you talk to our support first to enable backup encryption. So I'm leaving that to the next step where we just include the library in the binary.

**Pull request merged**
