### PR TITLE
Ensure 'stage' argument sanity (aka avoid misleading 'divio project pull db WRONGNAMEHERE')

### PR DESCRIPTION
**Pull request by filwaitman**

### CODE REVIEW

**Comment by kinkerl** [comment]
that is a very good idea!
we might have more environments than "test" and "live" in the future. can you please change the code that it will call a function to generate the choice list? that way it will be future proof and we can make the function generate the list later on.

**Comment by filwaitman** [comment]
@kinkerl nice! Yeah, I can wrap this in a function. Will do this shortly. =]

**Comment by filwaitman** [comment]
@kinkerl instead, why don't we create a simple global var for it?

**Comment by kinkerl** [comment]
@filwaitman because it could be dynamic and change per project. But looking at the implementation, this will require a differnet logic which closer resembles `@allow_remote_id_override` but this is already an improvement

**Pull request merged**
